#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install mycli <args...>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  which mycli >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -y mycli
  fi

  log::success "install mycli success."
}

run() {
  core $@
}

run $@
